
#ifndef _TA_VCODE_WIN_OPTIONS_H_
#define _TA_VCODE_WIN_OPTIONS_H_ 1
#pragma once

#define TA_BK_RGB RGB(244,247,252)	//±³¾°É«

#define _TA_VCODE_COUNT 5

#define _TA_VCODE_LEFT 5
#define _TA_VCODE_TOP 80
#define _TA_VCODE_WIDTH 180

#define _TA_VCODE_HEIGHT 40
#define _TA_VCODE_WITHBLANK_HEIGHT 45

#define _TA_VCODE_ALL_HEIGHT (_TA_VCODE_WITHBLANK_HEIGHT * _TA_VCODE_COUNT)

#define _TA_VCODE_FRIENDLY_VCODEAREA_WIDTH	240
#define _TA_VCODE_FRIENDLY_VCODEAREA_HEIGHT	90

#define _TA_VCODE_FRIENDLY_CHAR_STARTTOP	80
#define _TA_VCODE_FRIENDLY_CHAR_HEIGHT		80
#define _TA_VCODE_FRIENDLY_CHAR_WIDTH		80

//100x36
#define _TA_VCODE_FRIENDLY_VCODEAREA_SHOW_WIDTH		107
#define _TA_VCODE_FRIENDLY_VCODEAREA_SHOW_HEIGHT	40

#endif